import { type IRouter } from "express";
import {
  db,
  projectsTable,
  sourceInputsTable,
  generationRunsTable,
  assetCardsTable,
} from "@workspace/db";
import { eq, and, desc } from "drizzle-orm";
import { logger } from "../../lib/logger";
import { clampErrorMessage } from "../../lib/clamp-error";
import { regenerateSectionVisuals } from "../../lib/visual-assets";
import { MODEL, PROMPT_VERSION } from "./generation";
import { SLUG_PARAM } from "./params";
import { coerceStoryboardContent, serializeAssetCard } from "./serialization";
import { loadLaunchAngleText } from "./visual-context";

export function registerStoryboardImageRoutes(router: IRouter): void {
  // =====================================================================
  // POST /projects/:slug/sections/storyboard_cards/refresh-images
  //
  // Re-run only the image generation step for the existing storyboard
  // card without regenerating any frame text. Lets founders pull in
  // visibly better artwork from the new richer image-prompt builder
  // (hook + visual + on-screen text + voiceover) when their storyboard
  // text was already generated by an older prompt.
  //
  // Flow:
  //   1. Load project + existing storyboard card. 404 if either is missing.
  //   2. Read the current frames from the persisted content (after the
  //      storyboard coercion that maps legacy `caption` onto `voiceover`).
  //   3. Fan out one gpt-image-1 call per frame using the current text.
  //      Per-frame failures fall back to the *previous* imageUrl on that
  //      frame so a partial failure still leaves usable art instead of
  //      blowing away the existing image.
  //   4. Snapshot previousContent so the founder can Undo, then UPDATE
  //      the card in place with frames carrying their new imageUrl.
  // =====================================================================
  router.post(
    "/projects/:slug/sections/storyboard_cards/refresh-images",
    async (req, res) => {
      const parsed = SLUG_PARAM.safeParse(req.params);
      if (!parsed.success) {
        res.status(404).json({ error: "Project not found" });
        return;
      }
      const { slug } = parsed.data;

      const [project] = await db
        .select()
        .from(projectsTable)
        .where(eq(projectsTable.slug, slug))
        .limit(1);
      if (!project) {
        res.status(404).json({ error: "Project not found" });
        return;
      }

      const existing = await db
        .select()
        .from(assetCardsTable)
        .where(
          and(
            eq(assetCardsTable.projectId, project.id),
            eq(assetCardsTable.kind, "storyboard_cards"),
          ),
        )
        .orderBy(desc(assetCardsTable.createdAt))
        .limit(1);
      const existingCard = existing[0];
      if (!existingCard) {
        res.status(404).json({
          error:
            "No storyboard card to refresh images on. Generate the storyboard section first.",
        });
        return;
      }

      // Coerce so legacy `caption` payloads still render — the prompt
      // builder reads `voiceover`, so the legacy mapping matters here too.
      const existingContent = coerceStoryboardContent(
        (existingCard.content ?? {}) as Record<string, unknown>,
      );
      const framesRaw = (existingContent as { frames?: unknown }).frames;
      if (!Array.isArray(framesRaw) || framesRaw.length === 0) {
        res.status(404).json({
          error: "Storyboard card has no frames to refresh.",
        });
        return;
      }
      const frames = framesRaw as Array<{
        frame: number;
        hook?: string;
        visual: string;
        onScreenText?: string;
        voiceover?: string;
        imageUrl?: string | null;
      }>;

      // Look up the most recent source input only to attribute the run; the
      // refresh doesn't call the LLM so launch context isn't needed beyond
      // the launch angle (loaded below).
      const sourceInputs = await db
        .select({ id: sourceInputsTable.id })
        .from(sourceInputsTable)
        .where(eq(sourceInputsTable.projectId, project.id))
        .orderBy(desc(sourceInputsTable.createdAt))
        .limit(1);
      const sourceInputId = sourceInputs[0]?.id ?? existingCard.sourceInputId;

      const startedAt = new Date();
      let runId: string;
      try {
        const [run] = await db
          .insert(generationRunsTable)
          .values({
            projectId: project.id,
            sourceInputId,
            status: "running",
            model: MODEL,
            promptVersion: `${PROMPT_VERSION}-storyboard-images`,
            metadata: {
              regeneratedSection: "storyboard_cards",
              scope: "images",
            },
            startedAt,
          })
          .returning();
        runId = run!.id;
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Failed to record refresh run";
        logger.error(
          { err, projectId: project.id },
          "Storyboard image refresh run insert failed",
        );
        res.status(500).json({ error: message });
        return;
      }

      try {
        const angle = await loadLaunchAngleText(project.id);
        const visuals = await regenerateSectionVisuals({
          projectSlug: project.slug,
          launchAngle: angle,
          storyboardFrames: frames.map((f) => ({
            frame: f.frame,
            visual: f.visual,
            hook: f.hook,
            voiceover: f.voiceover,
            onScreenText: f.onScreenText,
          })),
        });

        const completedAt = new Date();
        const updatedCard = await db.transaction(async (tx) => {
          // Re-read the card inside the transaction and merge new image
          // URLs onto the LATEST persisted text. If a founder edited a
          // frame while images were being generated we still preserve
          // their newer text and only splice in the new imageUrls. This
          // shrinks the lost-update race window dramatically (mirrors
          // the landing-FAQ backfill pattern) without taking a row lock.
          const fresh = await tx
            .select()
            .from(assetCardsTable)
            .where(eq(assetCardsTable.id, existingCard.id))
            .limit(1);
          const freshCard = fresh[0];
          if (!freshCard) {
            throw new Error(
              "Storyboard card was removed before images could be saved",
            );
          }
          const freshContent = coerceStoryboardContent(
            (freshCard.content ?? {}) as Record<string, unknown>,
          );
          const freshFramesRaw = (freshContent as { frames?: unknown }).frames;
          const freshFrames = Array.isArray(freshFramesRaw)
            ? (freshFramesRaw as Array<{
                frame: number;
                imageUrl?: string | null;
              }>)
            : [];
          // Per-frame failure → keep the existing imageUrl so the
          // founder doesn't end up with a worse card than they started
          // with. Use the just-re-read fresh frame as the base.
          const refreshedFrames = freshFrames.map((f) => ({
            ...f,
            imageUrl:
              visuals.storyboardImages.get(f.frame) ?? f.imageUrl ?? null,
          }));
          const newPayload: Record<string, unknown> = {
            ...freshContent,
            frames: refreshedFrames,
          };
          const [row] = await tx
            .update(assetCardsTable)
            .set({
              content: newPayload,
              previousContent: (freshCard.content ?? {}) as Record<
                string,
                unknown
              >,
              previousUpdatedAt: freshCard.updatedAt,
              generationRunId: runId,
              sourceInputId,
              updatedAt: completedAt,
            })
            .where(eq(assetCardsTable.id, freshCard.id))
            .returning();
          await tx
            .update(generationRunsTable)
            .set({ status: "done", completedAt })
            .where(eq(generationRunsTable.id, runId));
          return row!;
        });

        res.status(200).json(serializeAssetCard(updatedCard));
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Image refresh failed";
        logger.error(
          { err, projectId: project.id, runId },
          "Storyboard image refresh failed",
        );
        try {
          await db
            .update(generationRunsTable)
            .set({
              status: "error",
              errorMessage: clampErrorMessage(message),
              completedAt: new Date(),
            })
            .where(eq(generationRunsTable.id, runId));
        } catch (dbErr) {
          logger.error(
            { err: dbErr, runId },
            "Failed to mark image refresh run as error",
          );
        }
        res.status(500).json({ error: message });
      }
    },
  );
}
